// Mocks generated by Mockito 5.4.4 from annotations
// in group_escape/test/create_trip_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:group_escape/models/trip_model.dart' as _i6;
import 'package:group_escape/services/firestore_service.dart' as _i5;
import 'package:group_escape/shared/firebase_authentication.dart' as _i2;
import 'package:group_escape/util/availability.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FirebaseAuthentication].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuthentication extends _i1.Mock
    implements _i2.FirebaseAuthentication {
  MockFirebaseAuthentication() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String currentUser() => (super.noSuchMethod(
        Invocation.method(
          #currentUser,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #currentUser,
            [],
          ),
        ),
      ) as String);

  @override
  _i4.Future<String?> createUser(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i5.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> subscribeToTopic(dynamic tripId) => (super.noSuchMethod(
        Invocation.method(
          #subscribeToTopic,
          [tripId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> sendNotification({required String? topic}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendNotification,
          [],
          {#topic: topic},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String> addTrip(_i6.TripModel? trip) => (super.noSuchMethod(
        Invocation.method(
          #addTrip,
          [trip],
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #addTrip,
            [trip],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> addAvailability(
    String? tripId,
    _i7.Availability? availability,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAvailability,
          [
            tripId,
            availability,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTrip(
    String? tripId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTrip,
          [
            tripId,
            userId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> checkIfExists(String? tripId) => (super.noSuchMethod(
        Invocation.method(
          #checkIfExists,
          [tripId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> addUserToTrip(
    String? tripId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addUserToTrip,
          [
            tripId,
            userId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> getUserName(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUserName,
          [userId],
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #getUserName,
            [userId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Stream<List<Map<String, dynamic>>> getTripsStream(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTripsStream,
          [userId],
        ),
        returnValue: _i4.Stream<List<Map<String, dynamic>>>.empty(),
      ) as _i4.Stream<List<Map<String, dynamic>>>);
}
