// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDidTGQTmJHFox4YuI_fkShz4BypIVg0NA',
    appId: '1:638295252137:web:cd33c36c94af3d83561db8',
    messagingSenderId: '638295252137',
    projectId: 'groupescape-7b6a4',
    authDomain: 'groupescape-7b6a4.firebaseapp.com',
    storageBucket: 'groupescape-7b6a4.appspot.com',
    measurementId: 'G-EQM97Q1DCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlyFyfbyFdKjZWbSqJD1koCQxrP1l-ofM',
    appId: '1:638295252137:android:089498855b9b7d5f561db8',
    messagingSenderId: '638295252137',
    projectId: 'groupescape-7b6a4',
    storageBucket: 'groupescape-7b6a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8nel-2cFZW2CXthibyQ3pgQoVj_c4ekY',
    appId: '1:638295252137:ios:0485b3f91d87675e561db8',
    messagingSenderId: '638295252137',
    projectId: 'groupescape-7b6a4',
    storageBucket: 'groupescape-7b6a4.appspot.com',
    iosBundleId: 'com.example.groupEscape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8nel-2cFZW2CXthibyQ3pgQoVj_c4ekY',
    appId: '1:638295252137:ios:0485b3f91d87675e561db8',
    messagingSenderId: '638295252137',
    projectId: 'groupescape-7b6a4',
    storageBucket: 'groupescape-7b6a4.appspot.com',
    iosBundleId: 'com.example.groupEscape',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDidTGQTmJHFox4YuI_fkShz4BypIVg0NA',
    appId: '1:638295252137:web:7cd2babe5a71296d561db8',
    messagingSenderId: '638295252137',
    projectId: 'groupescape-7b6a4',
    authDomain: 'groupescape-7b6a4.firebaseapp.com',
    storageBucket: 'groupescape-7b6a4.appspot.com',
    measurementId: 'G-PHYVB6YCP0',
  );

}